//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Case_Main
    {
        public string RootId { get; set; }
        public string CompanyNum { get; set; }
        public string BranchNum { get; set; }
        public string CaseNum { get; set; }
        public string UserName { get; set; }
        public string SerialNum { get; set; }
        public string OrgName { get; set; }
        public string FullAddress { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public Nullable<int> CaseFlag { get; set; }
        public Nullable<System.DateTime> recording_time { get; set; }
        public Nullable<System.DateTime> updated_time { get; set; }
        public string PropertyName { get; set; }
        public string OrgId { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> CommissionDate { get; set; }
        public string RecordNum { get; set; }
        public string NewProperty { get; set; }
        public Nullable<decimal> NewAnJieMoney { get; set; }
        public Nullable<System.DateTime> NPDateTime { get; set; }
        public int IsFromFirst { get; set; }
        public Nullable<int> isGSP { get; set; }
        public string ExchangeType { get; set; }
        public Nullable<int> IsNewHome { get; set; }
        public string MainUser_Name { get; set; }
        public string MainUser_ID { get; set; }
        public string MainUser_Code { get; set; }
        public string MainOrg_Name { get; set; }
        public string MainOrg_ID { get; set; }
        public string MainOrg_Code { get; set; }
        public string SourceFlag { get; set; }
        public string Delegation_Code { get; set; }
        public string IsSpecialCase { get; set; }
        public string OrgIdA { get; set; }
        public Nullable<System.DateTime> EarnestDate { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public string BUSISH_ID { get; set; }
        public string BUSIAR_ID { get; set; }
        public string BUSISWZ_ID { get; set; }
        public string BUSIWZ_ID { get; set; }
        public string BUSIBA_ID { get; set; }
    }
}
