//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CaseClient
    {
        public int Id { get; set; }
        public string RootID { get; set; }
        public string ctm_code { get; set; }
        public string cust_code { get; set; }
        public string cust_position { get; set; }
        public string name { get; set; }
        public string mobile { get; set; }
        public string cert_type { get; set; }
        public string cert_code { get; set; }
    }
}
